# Generated by Django 4.2.5 on 2023-10-19 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_comment_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "default_related_name": "blogs",
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
            },
        ),
        migrations.AlterModelOptions(
            name="blogger",
            options={
                "default_related_name": "bloggers",
                "verbose_name": "Blogger",
                "verbose_name_plural": "Bloggers",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "default_related_name": "comments",
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
    ]
